[tool.track-bump]
version = "0.1.0"
version_files = [
    "sub-project-1/pyproject.toml",
    "sub-project-2/pyproject.toml"
]
bump_message = "chore: release {current_version} → {new_version} [skip ci]"