[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "$version"
version_files = [
    "orb/pyproject.toml:version",
]
bump_message = "release $current_version → $new_version [skip ci]"
