version: 2.1


orbs:
  ci-tools: tracktor/ci-tools@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  test-python-commands:
    docker:
      - image: cimg/python:3.12.1-node
        environment:
          PYRIGHT_PYTHON_GLOBAL_NODE: true
    working_directory: ~/ci-tools-orb/projects/python
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/export-poetry
      - ci-tools/export-poetry:
          extras: "--without-hashes"
      - ci-tools/load-poetry-version
      - ci-tools/run-python-tests
      - ci-tools/run-python-tests:
          formatter: "ruff"

  test-docker-commands:
    docker:
      - image: cimg/base:current
    working_directory: ~/ci-tools-orb/projects/docker
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/build-docker:
          image_name: "tracktor/orb-test"
          registry_pwd: $DOCKER_HUB_PWD
          registry_user: $DOCKER_HUB_USER
      - ci-tools/build-docker:
          image_name: "tracktor/orb-test"
          publish: true
          registry_pwd: $DOCKER_HUB_PWD
          registry_user: $DOCKER_HUB_USER

  test-js-commands:
    docker:
      - image: cimg/node:18.20.4
    working_directory: ~/ci-tools-orb/projects/js
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/load-package-version
      - run:
          name: Check version
          command: echo $VERSION

  test-bump-version-python:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/ci-tools-orb/projects/python
    environment:
      CI_EMAIL: "test@test.test"
      CI_USER: "test"
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - run:
          name: "Install deps"
          command: poetry install
      - ci-tools/bump-version:
          branch: "main"
          lang: "python"
          dry_run: true

  test-bump-version-python-no-build:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/ci-tools-orb/projects/python
    environment:
      CI_EMAIL: "test@test.test"
      CI_USER: "test"
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - run:
          name: "Install deps"
          command: poetry install
      - ci-tools/bump-version:
          branch: "main"
          lang: "python"
          dry_run: true
          build: false

  test-bump-version-python-no-poetry:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/ci-tools-orb/projects/python-no-poetry
    environment:
      CI_EMAIL: "test@test.test"
      CI_USER: "test"
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - run:
          name: "Install deps"
          command: pip install commitizen==3.0.0
      - ci-tools/bump-version:
          branch: "main"
          lang: "python"
          dry_run: true
          use_poetry: false

  test-bump-version-js:
    docker:
      - image: cimg/node:18.20.4
    working_directory: ~/ci-tools-orb/projects/js
    environment:
      CI_EMAIL: "test@test.test"
      CI_USER: "test"
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - run:
          name: "Install deps"
          command: yarn install
      - ci-tools/bump-version:
          branch: "main"
          lang: "js"
          dry_run: true

  test-python-track-bump:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/ci-tools-orb/projects/python-track-bump
    environment:
      CI_USER_EMAIL: "test@test.test"
      CI_USER: "test"
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/track-bump:
          dry_run: true
          verbose: true
          default_branch: "main"
          branch: "main"

  test-docker-tag:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/ci-tools-orb/projects/python-track-bump
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/load-docker-tag

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-python-commands:
          filters: *filters
      - test-docker-commands:
          filters: *filters
      - test-js-commands:
          filters: *filters
      - test-bump-version-js:
          filters: *filters
      - test-bump-version-python:
          filters: *filters
      - test-bump-version-python-no-build:
          filters: *filters
      - test-bump-version-python-no-poetry:
          filters: *filters
      - test-python-track-bump:
          filters: *filters
      - test-docker-tag:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: tracktor/ci-tools
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-python-commands
            - test-docker-commands
            - test-js-commands
            - test-bump-version-js
            - test-bump-version-python
            - test-bump-version-python-no-poetry
            - test-bump-version-python-no-build
            - test-python-track-bump
            - test-docker-tag
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
