version: 2.1


orbs:
  ci-tools: tracktor/ci-tools@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  test-python-commands:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/ci-tools-orb/projects/python
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/export-poetry
      - ci-tools/export-poetry:
          extras: "--without-hashes"
      - ci-tools/load-poetry-version
      - ci-tools/run-python-tests

  test-docker-commands:
    docker:
      - image: cimg/base:current
    working_directory: ~/ci-tools-orb/projects/docker
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/build-docker:
          image_name: "tracktor/orb-test"
      - ci-tools/build-docker:
          image_name: "tracktor/orb-test"
          publish: true
          registry_pwd: $DOCKER_HUB_PWD
          registry_user: $DOCKER_HUB_USER

  test-js-commands:
    docker:
      - image: cimg/node:16.17.0
    working_directory: ~/ci-tools-orb/projects/js
    steps:
      - checkout:
          path: ~/ci-tools-orb
      - ci-tools/load-package-version

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-python-commands:
          filters: *filters
      - test-docker-commands:
          filters: *filters
      - test-js-commands:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: tracktor/ci-tools
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-python-commands
            - test-docker-commands
            - test-js-commands
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
